package inboundxml

import (
	"testing"
)

func TestNewResponse(t *testing.T) {
	var (
		response *Response
	)

	response = NewResponse()

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Say("Hello World", nil)

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Say>Hello World</Say></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Hangup(&HangupAttrs{})

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Say>Hello World</Say><Hangup /></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()

	response.Gather(NewSay("Meow", nil), nil)

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Gather><Say>Meow</Say></Gather></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Play("http://www.example.com/audio.mp3", nil)

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Play>http://www.example.com/audio.mp3</Play></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.Play("http://www.example.com/audio.mp3", &PlayAttrs{Loop: 1})

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Play loop=\"1\">http://www.example.com/audio.mp3</Play></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.Play("http://www.example.com/audio.mp3", &PlayAttrs{Digits: "w1"})

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Play digits=\"w1\">http://www.example.com/audio.mp3</Play></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.DTMF("w9174807478#")

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><DTMF>w9174807478#</DTMF></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.Ping("www.google.com", "POST")

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Ping method=\"POST\">www.google.com</Ping></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.Pause(3)

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Pause length=\"3\" /></Response>" {
		t.Errorf("Unexpected string generated by response %s", response.String())
	}

	response.Reset()
	response.Record(&RecordAttrs{MaxLength: 60})

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Record maxLength=\"60\" playBeep=\"false\" background=\"false\" trimSilence=\"false\" /></Response>" {
		t.Errorf("Unexpected string generated by response")
	}

	response.Reset()
	response.Record(&RecordAttrs{Action: "http://www.example.com/recording-callback", MaxLength: 60})

	if response.String() != "<?xml version=\"1.0\" encoding=\"utf-8\"?><Response><Record action=\"http://www.example.com/recording-callback\" maxLength=\"60\" playBeep=\"false\" background=\"false\" trimSilence=\"false\" /></Response>" {
		t.Errorf("Unexpected string generated by response")
	}
}
